version: "3.8"

services:
  app:
    depends_on:
      - postgres
      - adminer
    image: node:${NODE_CONTAINER_TAG}
    user: node
    ports:
      - 3000:3000 # Dev server port
      - 9229:9229 # Debugger port - see /.vscode/launch.json
    working_dir: ${APP_DIR} # For convenience in case need to `exec` into the container
    volumes:
      - ./app:${APP_DIR}
    environment:
      # See recommendations at: https://github.com/nodejs/docker-node/blob/main/docs/BestPractices.md
      NPM_CONFIG_PREFIX: ${NPM_CONFIG_PREFIX}
      PATH: ${REMOTE_PATH}:${NPM_CONFIG_PREFIX}/bin
    command: ./bin/zzzDO_NOT_RUN_MANUALLY

  postgres:
    image: postgres:${POSTGRES_CONTAINER_TAG}
    volumes:
      # Postgres default data files location: https://github.com/docker-library/docs/blob/master/postgres/README.md#pgdata
      - ./db-postgres:/var/lib/postgresql/data
    # user: 1000:1000
    environment:
      # Env var ref: https://github.com/docker-library/docs/blob/master/postgres/README.md#environment-variables
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}

  adminer:
    depends_on:
      - postgres
    image: adminer # Just use latest.
    volumes:
      # For custom files for plugins requiring parameters; see: https://hub.docker.com/_/adminer
      - ./adminer-plugins:/var/www/html/plugins-enabled
    ports:
      - 8080:8080
    environment:
      - ADMINER_PLUGINS=${ADMINER_PLUGINS}
      - ADMINER_DESIGN=${ADMINER_DESIGN}
