version: "3.8"

# networks:
#   supabase-dev:
#     name: supabase_network_supabase
#     external: true

services:
  app:
    image: node:${NODE_IMAGE_TAG}
    user: node
    # network_mode: "host"
    # extra_hosts:
    # #   - "host.docker.internal"
    #   - "dockerhost: ###.###.###"
    ports:
      - 3000:3000 # Dev server port
      - 9229:9229 # Debugger port - see /.vscode/launch.json
    working_dir: ${REMOTE_APP_DIR} # For convenience in case need to `exec` into the container
    volumes:
      - ./${LOCAL_APP_DIR}:${REMOTE_APP_DIR}
      - ./startup-scripts:/startup-scripts
      - ./volumes/npm-global:${NPM_CONFIG_PREFIX}
    environment:
      # See recommendations at: https://github.com/nodejs/docker-node/blob/main/docs/BestPractices.md
      NPM_CONFIG_PREFIX: ${NPM_CONFIG_PREFIX}
      CONFIGURED_REMOTE_PATH: ${REMOTE_PATH}
    command: bash -c 'for file in /startup-scripts/*.sh; do $$file; done'